config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :users
  resources :attendances
  resources :invitations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  has_many :attendances, foreign_key: :event_id, dependent: :destroy
  has_many :attendees, through: :attendances

  has_many :invitations, foreign_key: :event_id, dependent: :destroy
  has_many :invited_users, through: :invitations, source: :invitee

  scope :past_events, -> { where('date < ?', Date.today) }
  scope :future_events, -> { where('date > ?', Date.today) }
  scope :is_public, -> { where(is_private: false) }
  scope :is_private, -> { where(is_private: true) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :organizer, class_name: 'User'
  belongs_to :invitee, class_name: 'User'
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :events, foreign_key: :creator_id, dependent: :destroy

  has_many :attendances, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :attendances, source: :event, dependent: :destroy

  has_many :invitations_received, foreign_key: :invitee_id, dependent: :destroy, class_name: 'Invitation'
  has_many :invited_events, through: :invitations, source: :event
  has_many :invitations_sent, foreign_key: :organizer_id, dependent: :destroy, class_name: 'Invitation'

  scope :all_except, ->(user) { where.not(id: user) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.attendances.create(attend_params)

    # destroy the invite if the linke is coming from an invite 
    Invitation.find(params[:invitation_id]).destroy if params[:invitations]

    redirect_back(fallback_location: root_path)
  end

  def destroy
    @attendance = Attendance.find(params[:id])
    @attendance.destroy

    redirect_back(fallback_location: root_path)
  end

  private

  def attend_params
    params.permit(:event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]

  # GET /events or /events.json
  def index
    @events = Event.all.order(date: :desc)
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = current_user.events.build()
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :date, :location, :is_private)
    end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def new
    @users = User.all_except(current_user)
    @event = Event.find(params[:event_id])
    @invited_users = @event.invited_users
  end

  def create
    current_user.invitations_sent.create(create_params)

    redirect_back(fallback_location: root_path)
  end

  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.destroy

    redirect_back(fallback_location: root_path)
  end

  private

  def create_params
    params.require(:invitation).permit(:invitee_id, :event_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit delete]

  def show
    @created_events = @user.events.all
    @attended_events = @user.attended_events.all
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div class="card my-6" id="index-card">
  <div class="card-content">
    <div class="content">
      <p class='title is-size-5 has-text-weight-bold'>
        <%= event.name %>
      </p>
      <p class='subtitle has-text-weight-light is-italic is-size-7'>
        <%= event.location %> on <%= event.date.strftime("%e %B, %Y - %A") %>
      </p>

      <p>
        Organized by: <%= link_to event.creator.name, event.creator %> 
      </p>
    </div>
  </div>
  <div class="card-footer">
    <p class="card-footer-item">
      <% if event.attendees.include? current_user %>
        <%= link_to attendance_path(current_user.attendances.find_by(event_id: event.id)), method: :delete do %>
          <span>
            Cancel Attendance
          </span>
        <% end %>
      <% else %>
        <%= link_to attendances_path(event_id: event.id), method: :post do %>
          <span>
            Attend 
          </span>
        <% end %>
      <% end %>
    </p>
    <p class="card-footer-item">
      <%= link_to event do %>
        <span>Show</span>
      <% end %>
    </p>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :is_private, 'Private' %> 
    <%= form.check_box :is_private %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="columns">
  <div class="column is-three-quarters">
    <!-- public events here 
    Event name 
    Date
    Location
    Creator
    Kung ilan na yung sasali

    sort by date of occurence
    -->
    <div class="container">
      <% if @events.any? %>
        <%= render(@events) %>
      <% else %>
        <div class="card my-6" id="index-card">
          <div class="card-content">
            <div class="content">
              <p class="has-text-weight-light">No events currently available</p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="column">
    <article class="panel my-6 mr-3">
      <p class="panel-heading">Invitations</p>
        <% if user_signed_in? %>
          <% case current_user.invitations_received.any? %>
            <% when true %>
              <%= render(partial: 'invitations/invitation', collection: current_user.invitations_received) %> 
            <% else %>
              <p class='is-italic is-small panel-block'>No Invitations yet</p>
            <% end %>
        <% else %>
          <p class='is-italic is-small panel-block'>Log in to view invitations</p>
        <% end %>
    </article>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Creator:</strong>
  <%= link_to @event.creator.email, user_path(@event.creator) %>
</p>

<p>
  <strong>Data:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>


<%
  user_attending = @event.attendees.include? current_user 
  attend_label = user_attending ? 'Cancel' : 'Attend'
  attend_method = user_attending ? :delete : :post 
  path = user_attending ? attendance_path(current_user.attendances.find_by(event_id: @event.id)) : attendances_path(event_id: @event.id)
%>
<%= link_to attend_label, path, method: attend_method %>
<%= link_to 'Edit', edit_event_path(@event) %>

<% if @event.attendances.any?%>
  <br>
  <br>
  <strong>Attendance</strong>
  <ul>
    <% @event.attendees.each do |attendee| %>  
      <li><%= attendee.name %></li>
    <% end %>
  </ul>
  <br>
<% end %>

<%= link_to 'Back', events_path %>

app/views/invitations/_invitation.html.erb
<p class="panel-block" id="invitation-panel">
    <span>
      <%= link_to invitation.event do %>
        <span class="has-text-weight-semibold"><%= invitation.event.name %></span>
      <% end %>
      | 
      <%= link_to invitation.organizer do %>
        <span class="has-text-weight-light is-size-7"><%= invitation.organizer.name%></span>
      <% end %>
    </span> 
    <span>
      <%= link_to attendances_path(event_id: invitation.event.id, invitation_id: invitation.id ), method: :post do %>
        <button class="button is-dark is-small mx-1">Accept</button>
      <% end %>
      <%= link_to invitation_path(invitation), method: :delete do %>
        <button class="button is-dark is-small mx-1">Reject</button>
      <% end %>
    </span>
</p>

app/views/invitations/new.html.erb
<h1><strong> <%= @event.name %> Invitations </strong></h1>

<% @users.each do |user| %>
  <%= user.name %>  |
  <% if @invited_users.include? user %>
    <%= link_to 'Uninvite', invitation_path(@event.invitations.find_by(invitee_id: user)), method: :delete %>
  <% else %>
    <%= link_to 'Invite', invitations_path(invitation: { invitee_id: user.id, event_id: @event.id }), method: :post %>
  <% end%>
  <br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="app">
      <% if flash[:notice] %>
        <div class="notification is-primary global-notification">
          <p class="notice"><%= notice %></p>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="notification is-danger global-notification">
          <p class="alert"><%= alert %></p>
        </div>
      <% end %>

      <div class="navbar is-dark" role="navigation" aria-label = "main navigation" >
        <div class="navbar-brand">
          <%= link_to root_path, class: 'navbar-item' do %>
            <strong class="is-size-5">Private-Events</strong>
          <% end %>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <% if user_signed_in? %>
                  <%= link_to 'Profile', current_user, class: 'button is-light' %>
                  <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'button is-light' %>
              <% else %>
                  <%= link_to 'Log in', new_user_session_path, class: 'button is-light '%>
                  <%= link_to 'Sign up', new_user_registration_path, class: 'button is-light ' %>
              <% end %>
            
            </div>
          </div>
        </div>
      </div>

      <%= yield %>

      <footer class="footer py-5">
        <div class="content has-text-centered">
          <%= link_to "Private Events", 
            "https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/private-events", 
            class: "has-text-weight-semibold has-text-info", target: "_blank"
          %>
          implementation by 
          <%= link_to "derUbermenk", "https://github.com/derUbermenk", class: "has-text-info", target: "_blank" %>
        </div> 
      </footer>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<div>
  <%= "#{@user.name} | #{@user.events.count}" %><br>
  <%= link_to 'Create Event', new_event_path %>
</div>

<div>
  <strong>Events Created</strong>
  <div>
    <% if @created_events.any? %>
      <ul>
      <% @created_events.each do |event| %>
        <li><%= "#{event.name} | #{event.date}" %> | 
          <% if current_user == @user %>
            <%= link_to 'Edit', edit_event_path(event) %> 
            <% if event.is_private == true %>
              | <%= link_to 'Invite People', new_invitation_path(event_id: event.id) %>
            <% end %>
          <% end %>
        </li>
      <% end %>
      </ul>
    <% else %>
      <i>No events created</i>
    <% end %>
  </div>
</div>

<div>
  <strong>Events Joined</strong>
  <div>
    <% if @attended_events.any? %>
      <strong>Future events</strong>
      <ul>
      <% @attended_events.future_events.each do |future_event| %>
        <li>
            <%= link_to future_event.name, future_event %>
            <%= " | #{future_event.date}" %>
        </li>
      <% end %>
      </ul>
      <strong>Past events</strong>
      <ul>
      <% @attended_events.past_events.each do |past_event| %>
        <li>
            <%= link_to past_event.name, past_event%>
            <%= " | #{past_event.date}" %>
        </li>
      <% end %>
      </ul>
    <% else %>
      <i>No events attended</i>
    <% end %>
  </div>
</div>

<% if current_user == @user %>
  <div>
    <strong>Invites</strong><br>
    <% current_user.invitations_received.each do |invitation| %>
      <%= invitation.event.name %> 
      <br>
      <%= link_to attendances_path(event_id: invitation.event.id, invitation_id: invitation.id ), method: :post do %>
        <button>Accept</button>
      <% end %>
      <%= link_to invitation_path(invitation), method: :delete do %>
        <button>Reject</button>
      <% end %>
      <br>
      <br>
    <% end %>
    <br>
  </div>
<% end %>